-- Generated by Oracle SQL Developer Data Modeler 18.1.0.082.1041
--   at:        2025-10-08 22:29:38 PKT
--   site:      Oracle Database 11g
--   type:      Oracle Database 11g



CREATE TABLE authors (
    author_id    INTEGER NOT NULL,
    first_name   VARCHAR2(25) NOT NULL,
    last_name    VARCHAR2(25) NOT NULL,
    birth_date   DATE
);

ALTER TABLE authors ADD CONSTRAINT authors_pk PRIMARY KEY ( author_id );

CREATE TABLE books (
    book_id             INTEGER NOT NULL,
    title               VARCHAR2(50) NOT NULL,
    publication_date    DATE,
    available_copies    INTEGER NOT NULL,
    authors_author_id   INTEGER NOT NULL
);

ALTER TABLE books ADD CONSTRAINT books_pk PRIMARY KEY ( book_id );

CREATE TABLE borrowedbooks (
    loan_id             INTEGER NOT NULL,
    loan_date           DATE NOT NULL,
    return_date         DATE NOT NULL,
    returned            VARCHAR2(1) NOT NULL,
    books_book_id       INTEGER NOT NULL,
    author_id           INTEGER NOT NULL,
    patrons_patron_id   INTEGER NOT NULL
);

ALTER TABLE borrowedbooks ADD CONSTRAINT borrowedbooks_pk PRIMARY KEY ( loan_id );

CREATE TABLE patrons (
    patron_id    INTEGER NOT NULL,
    first_name   VARCHAR2(25) NOT NULL,
    last_name    VARCHAR2(25) NOT NULL,
    email        VARCHAR2(50)
);

ALTER TABLE patrons ADD CONSTRAINT patrons_pk PRIMARY KEY ( patron_id );

ALTER TABLE books
    ADD CONSTRAINT books_authors_fk FOREIGN KEY ( authors_author_id )
        REFERENCES authors ( author_id );

ALTER TABLE borrowedbooks
    ADD CONSTRAINT borrowedbooks_books_fk FOREIGN KEY ( books_book_id )
        REFERENCES books ( book_id );

ALTER TABLE borrowedbooks
    ADD CONSTRAINT borrowedbooks_patrons_fk FOREIGN KEY ( patrons_patron_id )
        REFERENCES patrons ( patron_id );



-- Oracle SQL Developer Data Modeler Summary Report: 
-- 
-- CREATE TABLE                             4
-- CREATE INDEX                             0
-- ALTER TABLE                              7
-- CREATE VIEW                              0
-- ALTER VIEW                               0
-- CREATE PACKAGE                           0
-- CREATE PACKAGE BODY                      0
-- CREATE PROCEDURE                         0
-- CREATE FUNCTION                          0
-- CREATE TRIGGER                           0
-- ALTER TRIGGER                            0
-- CREATE COLLECTION TYPE                   0
-- CREATE STRUCTURED TYPE                   0
-- CREATE STRUCTURED TYPE BODY              0
-- CREATE CLUSTER                           0
-- CREATE CONTEXT                           0
-- CREATE DATABASE                          0
-- CREATE DIMENSION                         0
-- CREATE DIRECTORY                         0
-- CREATE DISK GROUP                        0
-- CREATE ROLE                              0
-- CREATE ROLLBACK SEGMENT                  0
-- CREATE SEQUENCE                          0
-- CREATE MATERIALIZED VIEW                 0
-- CREATE SYNONYM                           0
-- CREATE TABLESPACE                        0
-- CREATE USER                              0
-- 
-- DROP TABLESPACE                          0
-- DROP DATABASE                            0
-- 
-- REDACTION POLICY                         0
-- 
-- ORDS DROP SCHEMA                         0
-- ORDS ENABLE SCHEMA                       0
-- ORDS ENABLE OBJECT                       0
-- 
-- ERRORS                                   0
-- WARNINGS                                 0


INSERT INTO authors (author_id, first_name, last_name, birth_date)
VALUES (1, 'Sohail', 'Ahmed', TO_DATE('2000-01-02', 'YYYY-MM-DD'));

INSERT INTO books (book_id, title, publication_date, available_copies, authors_author_id)
VALUES (1, 'The Catcher in the Rye', TO_DATE('2005-07-16', 'YYYY-MM-DD'), 5, 1);

INSERT INTO patrons (patron_id, first_name, last_name, email)
VALUES (1, 'Mohammad', 'Nadeem', 'm.nadeem@example.com');

ALTER TABLE borrowedbooks
MODIFY (return_date NULL);

INSERT INTO borrowedbooks (loan_id, loan_date, return_date, returned, books_book_id, author_id, patrons_patron_id)
-- Generated by Oracle SQL Developer Data Modeler 18.1.0.082.1041
--   at:        2025-10-08 22:29:38 PKT
--   site:      Oracle Database 11g
--   type:      Oracle Database 11g



CREATE TABLE authors (
    author_id    INTEGER NOT NULL,
    first_name   VARCHAR2(25) NOT NULL,
    last_name    VARCHAR2(25) NOT NULL,
    birth_date   DATE
);

ALTER TABLE authors ADD CONSTRAINT authors_pk PRIMARY KEY ( author_id );

CREATE TABLE books (
    book_id             INTEGER NOT NULL,
    title               VARCHAR2(50) NOT NULL,
    publication_date    DATE,
    available_copies    INTEGER NOT NULL,
    authors_author_id   INTEGER NOT NULL
);

ALTER TABLE books ADD CONSTRAINT books_pk PRIMARY KEY ( book_id );

CREATE TABLE borrowedbooks (
    loan_id             INTEGER NOT NULL,
    loan_date           DATE NOT NULL,
    return_date         DATE NOT NULL,
    returned            VARCHAR2(1) NOT NULL,
    books_book_id       INTEGER NOT NULL,
    author_id           INTEGER NOT NULL,
    patrons_patron_id   INTEGER NOT NULL
);

ALTER TABLE borrowedbooks ADD CONSTRAINT borrowedbooks_pk PRIMARY KEY ( loan_id );

CREATE TABLE patrons (
    patron_id    INTEGER NOT NULL,
    first_name   VARCHAR2(25) NOT NULL,
    last_name    VARCHAR2(25) NOT NULL,
    email        VARCHAR2(50)
);

ALTER TABLE patrons ADD CONSTRAINT patrons_pk PRIMARY KEY ( patron_id );

ALTER TABLE books
    ADD CONSTRAINT books_authors_fk FOREIGN KEY ( authors_author_id )
        REFERENCES authors ( author_id );

ALTER TABLE borrowedbooks
    ADD CONSTRAINT borrowedbooks_books_fk FOREIGN KEY ( books_book_id )
        REFERENCES books ( book_id );

ALTER TABLE borrowedbooks
    ADD CONSTRAINT borrowedbooks_patrons_fk FOREIGN KEY ( patrons_patron_id )
        REFERENCES patrons ( patron_id );



-- Oracle SQL Developer Data Modeler Summary Report: 
-- 
-- CREATE TABLE                             4
-- CREATE INDEX                             0
-- ALTER TABLE                              7
-- CREATE VIEW                              0
-- ALTER VIEW                               0
-- CREATE PACKAGE                           0
-- CREATE PACKAGE BODY                      0
-- CREATE PROCEDURE                         0
-- CREATE FUNCTION                          0
-- CREATE TRIGGER                           0
-- ALTER TRIGGER                            0
-- CREATE COLLECTION TYPE                   0
-- CREATE STRUCTURED TYPE                   0
-- CREATE STRUCTURED TYPE BODY              0
-- CREATE CLUSTER                           0
-- CREATE CONTEXT                           0
-- CREATE DATABASE                          0
-- CREATE DIMENSION                         0
-- CREATE DIRECTORY                         0
-- CREATE DISK GROUP                        0
-- CREATE ROLE                              0
-- CREATE ROLLBACK SEGMENT                  0
-- CREATE SEQUENCE                          0
-- CREATE MATERIALIZED VIEW                 0
-- CREATE SYNONYM                           0
-- CREATE TABLESPACE                        0
-- CREATE USER                              0
-- 
-- DROP TABLESPACE                          0
-- DROP DATABASE                            0
-- 
-- REDACTION POLICY                         0
-- 
-- ORDS DROP SCHEMA                         0
-- ORDS ENABLE SCHEMA                       0
-- ORDS ENABLE OBJECT                       0
-- 
-- ERRORS                                   0
-- WARNINGS                                 0


INSERT INTO authors (author_id, first_name, last_name, birth_date)
VALUES (1, 'Sohail', 'Ahmed', TO_DATE('2000-01-02', 'YYYY-MM-DD'));

INSERT INTO books (book_id, title, publication_date, available_copies, authors_author_id)
VALUES (1, 'The Catcher in the Rye', TO_DATE('2005-07-16', 'YYYY-MM-DD'), 5, 1);

INSERT INTO patrons (patron_id, first_name, last_name, email)
VALUES (1, 'Mohammad', 'Nadeem', 'm.nadeem@example.com');

ALTER TABLE borrowedbooks
MODIFY (return_date NULL);

INSERT INTO borrowedbooks (loan_id, loan_date, return_date, returned, books_book_id, author_id, patrons_patron_id)
VALUES (1, TO_DATE('2023-03-15', 'YYYY-MM-DD'), NULL, 'N', 1, 1, 1);

UPDATE books
SET available_copies  = 4
WHERE title = 'The Catcher in the Rye';

UPDATE borrowedbooks
SET returned = 'Y', return_date = TO_DATE('2023-03-15', 'YYYY-MM-DD')
WHERE patrons_patron_id = 1 AND books_book_id = 1;

UPDATE books
SET available_copies  = 5
WHERE title = 'The Catcher in the Rye';

SELECT 
    a.first_name || ' ' || a.last_name AS author_full_name,
    UPPER(b.title) AS book_title, 
    p.first_name || ' '  ||p.last_name AS patron_name,
    b.book_id,
    bb.returned,
    TO_CHAR(bb.loan_date, 'DY, DD-MON-YYYY') AS loan_date_with_day
FROM borrowedbooks bb
JOIN books b ON bb.books_book_id = b.book_id
JOIN authors a ON bb.author_id = a.author_id
JOIN patrons p ON bb.patrons_patron_id = p.patron_id;




