-- Generated by Oracle SQL Developer Data Modeler 18.1.0.082.1041
--   at:        2025-10-08 17:53:58 PKT
--   site:      Oracle Database 11g
--   type:      Oracle Database 11g

CREATE TABLE class (
    classid                 INTEGER NOT NULL,
    classcode               VARCHAR2(20) NOT NULL,
    begindate               DATE NOT NULL,
    enddate                 DATE NOT NULL,
    professor_professorid   INTEGER NOT NULL,
    subject_subjectid       INTEGER NOT NULL
);

ALTER TABLE class ADD CONSTRAINT class_pk PRIMARY KEY ( classid );

CREATE TABLE classstudent (
    classstudentid      INTEGER NOT NULL,
    student_studentid   INTEGER NOT NULL,
    class_classid       INTEGER NOT NULL
);

ALTER TABLE classstudent ADD CONSTRAINT classstudent_pk PRIMARY KEY ( classstudentid );

CREATE TABLE professor (
    professorid      INTEGER NOT NULL,
    professorname    VARCHAR2(100) NOT NULL,
    professoremail   VARCHAR2(100) NOT NULL,
    professorphone   VARCHAR2(20) NOT NULL
);

ALTER TABLE professor ADD CONSTRAINT professor_pk PRIMARY KEY ( professorid );

CREATE TABLE professorsubject (
    professorsubject        INTEGER NOT NULL,
    subject_subjectid       INTEGER NOT NULL,
    professor_professorid   INTEGER NOT NULL
);

ALTER TABLE professorsubject ADD CONSTRAINT professorsubject_pk PRIMARY KEY ( professorsubject );

CREATE TABLE student (
    studentid         INTEGER NOT NULL,
    studentname       VARCHAR2(100) NOT NULL,
    studentemail      VARCHAR2(100) NOT NULL,
    studentphone      VARCHAR2(20) NOT NULL,
    studentbirthday   DATE NOT NULL
);

ALTER TABLE student ADD CONSTRAINT student_pk PRIMARY KEY ( studentid );

CREATE TABLE subject (
    subjectid     INTEGER NOT NULL,
    subjectname   VARCHAR2(100) NOT NULL
);

ALTER TABLE subject ADD CONSTRAINT subject_pk PRIMARY KEY ( subjectid );

ALTER TABLE class
    ADD CONSTRAINT class_professor_fk FOREIGN KEY ( professor_professorid )
        REFERENCES professor ( professorid );

ALTER TABLE class
    ADD CONSTRAINT class_subject_fk FOREIGN KEY ( subject_subjectid )
        REFERENCES subject ( subjectid );

ALTER TABLE classstudent
    ADD CONSTRAINT classstudent_class_fk FOREIGN KEY ( class_classid )
        REFERENCES class ( classid );

ALTER TABLE classstudent
    ADD CONSTRAINT classstudent_student_fk FOREIGN KEY ( student_studentid )
        REFERENCES student ( studentid );

ALTER TABLE professorsubject
    ADD CONSTRAINT professorsubject_professor_fk FOREIGN KEY ( professor_professorid )
        REFERENCES professor ( professorid );

ALTER TABLE professorsubject
    ADD CONSTRAINT professorsubject_subject_fk FOREIGN KEY ( subject_subjectid )
        REFERENCES subject ( subjectid );



-- Oracle SQL Developer Data Modeler Summary Report: 
-- 
-- CREATE TABLE                             6
-- CREATE INDEX                             0
-- ALTER TABLE                             12
-- CREATE VIEW                              0
-- ALTER VIEW                               0
-- CREATE PACKAGE                           0
-- CREATE PACKAGE BODY                      0
-- CREATE PROCEDURE                         0
-- CREATE FUNCTION                          0
-- CREATE TRIGGER                           0
-- ALTER TRIGGER                            0
-- CREATE COLLECTION TYPE                   0
-- CREATE STRUCTURED TYPE                   0
-- CREATE STRUCTURED TYPE BODY              0
-- CREATE CLUSTER                           0
-- CREATE CONTEXT                           0
-- CREATE DATABASE                          0
-- CREATE DIMENSION                         0
-- CREATE DIRECTORY                         0
-- CREATE DISK GROUP                        0
-- CREATE ROLE                              0
-- CREATE ROLLBACK SEGMENT                  0
-- CREATE SEQUENCE                          0
-- CREATE MATERIALIZED VIEW                 0
-- CREATE SYNONYM                           0
-- CREATE TABLESPACE                        0
-- CREATE USER                              0
-- 
-- DROP TABLESPACE                          0
-- DROP DATABASE                            0
-- 
-- REDACTION POLICY                         0
-- 
-- ORDS DROP SCHEMA                         0
-- ORDS ENABLE SCHEMA                       0
-- ORDS ENABLE OBJECT                       0
-- 
-- ERRORS                                   0
-- WARNINGS                                 0


DROP TABLE subject CASCADE CONSTRAINTS
DROP TABLE professor CASCADE CONSTRAINTS


