-- Generated by Oracle SQL Developer Data Modeler 18.1.0.082.1041
--   at:        2025-10-03 07:09:57 PKT
--   site:      Oracle Database 11g
--   type:      Oracle Database 11g



CREATE TABLE city (
    city_code   INTEGER NOT NULL,
    city_name   VARCHAR2(50) NOT NULL,
    date_time   DATE
);

ALTER TABLE city ADD CONSTRAINT city_pk PRIMARY KEY ( city_code );

CREATE TABLE country (
    country_code   INTEGER NOT NULL,
    country_name   VARCHAR2(50) NOT NULL,
    date_time      DATE
);

ALTER TABLE country ADD CONSTRAINT country_pk PRIMARY KEY ( country_code );

CREATE TABLE employee (
    employee_id                     INTEGER NOT NULL,
    firstname                       VARCHAR2(20) NOT NULL,
    lastname                        VARCHAR2(20) NOT NULL,
    fullname                        VARCHAR2(50) NOT NULL,
    date_time                       DATE,
    state_state_code                INTEGER NOT NULL,
    city_city_code                  INTEGER NOT NULL,
    country_country_code            INTEGER NOT NULL,
    employee_employee_id            INTEGER NOT NULL,
    employee_state_state_code       INTEGER NOT NULL,
    employee_city_city_code         INTEGER NOT NULL,
    employee_country_country_code   INTEGER NOT NULL
);

ALTER TABLE employee
    ADD CONSTRAINT employee_pk PRIMARY KEY ( employee_id,
                                             state_state_code,
                                             city_city_code,
                                             country_country_code );

CREATE TABLE employer (
    employer_id     INTEGER NOT NULL,
    employer_name   VARCHAR2(100) NOT NULL,
    date_time       DATE
);

ALTER TABLE employer ADD CONSTRAINT employer_pk PRIMARY KEY ( employer_id );

CREATE TABLE hiring (
    date_time                       DATE,
    employee_employee_id            INTEGER NOT NULL,
    employee_state_state_code       INTEGER NOT NULL,
    employee_city_city_code         INTEGER NOT NULL,
    employee_country_country_code   INTEGER NOT NULL,
    employer_employer_id            INTEGER NOT NULL
);

ALTER TABLE hiring
    ADD CONSTRAINT hiring_pk PRIMARY KEY ( employee_employee_id,
                                           employee_state_state_code,
                                           employee_city_city_code,
                                           employee_country_country_code,
                                           employer_employer_id );

CREATE TABLE state (
    state_code   INTEGER NOT NULL,
    state_name   VARCHAR2(50) NOT NULL,
    date_time    DATE
);

ALTER TABLE state ADD CONSTRAINT state_pk PRIMARY KEY ( state_code );

ALTER TABLE employee
    ADD CONSTRAINT employee_city_fk FOREIGN KEY ( city_city_code )
        REFERENCES city ( city_code );

ALTER TABLE employee
    ADD CONSTRAINT employee_country_fk FOREIGN KEY ( country_country_code )
        REFERENCES country ( country_code );

ALTER TABLE employee
    ADD CONSTRAINT employee_employee_fk FOREIGN KEY ( employee_employee_id,
                                                      employee_state_state_code,
                                                      employee_city_city_code,
                                                      employee_country_country_code )
        REFERENCES employee ( employee_id,
                              state_state_code,
                              city_city_code,
                              country_country_code );

ALTER TABLE employee
    ADD CONSTRAINT employee_state_fk FOREIGN KEY ( state_state_code )
        REFERENCES state ( state_code );

ALTER TABLE hiring
    ADD CONSTRAINT hiring_employee_fk FOREIGN KEY ( employee_employee_id,
                                                    employee_state_state_code,
                                                    employee_city_city_code,
                                                    employee_country_country_code )
        REFERENCES employee ( employee_id,
                              state_state_code,
                              city_city_code,
                              country_country_code );

ALTER TABLE hiring
    ADD CONSTRAINT hiring_employer_fk FOREIGN KEY ( employer_employer_id )
        REFERENCES employer ( employer_id );



-- Oracle SQL Developer Data Modeler Summary Report: 
-- 
-- CREATE TABLE                             6
-- CREATE INDEX                             0
-- ALTER TABLE                             12
-- CREATE VIEW                              0
-- ALTER VIEW                               0
-- CREATE PACKAGE                           0
-- CREATE PACKAGE BODY                      0
-- CREATE PROCEDURE                         0
-- CREATE FUNCTION                          0
-- CREATE TRIGGER                           0
-- ALTER TRIGGER                            0
-- CREATE COLLECTION TYPE                   0
-- CREATE STRUCTURED TYPE                   0
-- CREATE STRUCTURED TYPE BODY              0
-- CREATE CLUSTER                           0
-- CREATE CONTEXT                           0
-- CREATE DATABASE                          0
-- CREATE DIMENSION                         0
-- CREATE DIRECTORY                         0
-- CREATE DISK GROUP                        0
-- CREATE ROLE                              0
-- CREATE ROLLBACK SEGMENT                  0
-- CREATE SEQUENCE                          0
-- CREATE MATERIALIZED VIEW                 0
-- CREATE SYNONYM                           0
-- CREATE TABLESPACE                        0
-- CREATE USER                              0
-- 
-- DROP TABLESPACE                          0
-- DROP DATABASE                            0
-- 
-- REDACTION POLICY                         0
-- 
-- ORDS DROP SCHEMA                         0
-- ORDS ENABLE SCHEMA                       0
-- ORDS ENABLE OBJECT                       0
-- 
-- ERRORS                                   0
-- WARNINGS                                 0

DROP TABLE hiring CASCADE CONSTRAINTS;

CREATE TABLE salary (
    salary_amount NUMBER(10, 2) NOT NULL,
    contract_period NUMBER NOT NULL, --- in days
    employee_id INTEGER NOT NULL,
    state_state_code INTEGER NOT NULL,
    city_city_code INTEGER NOT NULL,
    country_country_code INTEGER NOT NULL,
    employer_id INTEGER NOT NULL,
    
    -- Primary key = employee + employer (composite key like HIRING)
    CONSTRAINT salary_pk PRIMARY KEY (
        employee_id,
        state_state_code,
        city_city_code,
        country_country_code,
        employer_id
    ),
    
    -- Foreign key to EMPLOYEE
    CONSTRAINT salary_employee_fk FOREIGN KEY (
        employee_id,
        state_state_code,
        city_city_code,
        country_country_code
    )
    REFERENCES employee (
        employee_id,
        state_state_code,
        city_city_code,
        country_country_code
    ),
    
    -- Foreign key to EMPLOYER
    CONSTRAINT salary_employer_fk FOREIGN KEY (employer_id)
    REFERENCES employer (employer_id)
);

DROP TABLE employer CASCADE CONSTRAINTS;



